title: "TAB"
theme: midnight
remote_theme: pages-themes/midnight@v0.2.0

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S1-CS2103T-T17-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
  - jekyll-remote-theme # add this line to the plugins list if you already have one
